---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.18.0
directories:
- path: config/upstream
  contents:
  - path: .
    githubRelease:
      slug: vmware-tanzu/carvel-kapp-controller
      tag: v0.27.0
      disableAutoChecksumValidation: true
    includePaths:
    - release.yml