#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ if data.values.kappController.createNamespace:
#@overlay/match by=overlay.subset({"kind":"Namespace","metadata":{"name": "kapp-controller"}}),expects="1+"
---
metadata:
  name: kapp-controller
#@ else:
#@overlay/match by=overlay.subset({"kind":"Namespace","metadata":{"name": "kapp-controller"}}),expects="1+"
#@overlay/remove
---
#@ end

#@overlay/match by=overlay.subset({"kind":"ConfigMap","metadata":{"name": "kapp-controller-config"}})
---
metadata:
  namespace: kapp-controller

#@overlay/match by=overlay.subset({"kind": "ServiceAccount","metadata": {"name": "kapp-controller-sa"}}),expects="1+"
---
metadata:
  namespace: kapp-controller

#@overlay/match by=overlay.subset({"kind": "ClusterRoleBinding","metadata": {"name": "kapp-controller-cluster-role-binding"}}),expects="1+"
---
subjects:
#@overlay/match by=overlay.subset({"kind": "ServiceAccount"}),expects="1+"
- namespace: kapp-controller

#@overlay/match by=overlay.subset({"kind":"Deployment","metadata":{"name": "kapp-controller"}})
---
metadata:
  namespace: kapp-controller
