#@data/values
#@overlay/match-child-defaults missing_ok=True

---
kappController:
  namespace: kapp-controller
  createNamespace: true
  image:
    repository: registry.tkg.vmware.run/tkg
    path: kapp-controller
    tag: v0.16.0_vmware.1
    pullPolicy: IfNotPresent
  deployment:
    hostNetwork: null
    priorityClassName: null
    concurrency: 2
  config:
    caCerts: ""
    httpProxy: ""
    httpsProxy: ""
    noProxy: ""
